### ISSUE TITLE
Cannot read property 'loader' of undefined

### ISSUE THREAD

**Issue by davidwindell** [yireo-training/vsf-yireo-theme#2]
Thanks for your work on this, it's a great idea.

I've followed the README step-by-step using the latest capybara master but get the error below:

```
ℹ ｢wdm｣: Compiled successfully.
[module] VS Modules registration finished. { succesfulyRegistered: '0 / 0', registrationOrder: [] }
Calling asyncData in Home (theme) null
[vuex] unknown action type: homepage/fetchNewCollection
[vuex] unknown action type: promoted/updateHeadImage
[vuex] unknown action type: instagram/updateInstagramImages
Top-most asyncData executed null
[vuex] unknown action type: promoted/updatePromotedOffers
Result from ES for 79b9057612ca78b38884c4ce593fa397cd122e7285ff5be0e91b472a (category),  ms=757 null
[Vue warn]: Error in render: "TypeError: Cannot read property 'loader' of undefined"

found in

---> <MLoader> at src/themes/capybara/components/molecules/m-loader.vue
       <DefaultLayout> at src/themes/capybara/layouts/Default.vue
         <App> at src/themes/capybara/App.vue
           <Root>
Error during render : /
TypeError: Cannot read property 'loader' of undefined
    at VueComponent.isVisible (src/themes/capybara/components/molecules/m-loader.vue:25:0)
    at VueComponent.mappedState (/projects/example-vue/node_modules/vuex/dist/vuex.common.js:856:15)
    at VueComponent.computedGetter [as isVisible] (/projects/example-vue/node_modules/vue/dist/vue.runtime.common.dev.js:4831:15)
    at Object.get (/projects/example-vue/node_modules/vue/dist/vue.runtime.common.dev.js:2068:20)
    at Proxy.render (src/themes/capybara/components/molecules/m-loader.vue?26a5:12:0)
    at VueComponent.Vue._render (/projects/example-vue/node_modules/vue/dist/vue.runtime.common.dev.js:3538:22)
    at resolve (/projects/example-vue/node_modules/vue-server-renderer/build.dev.js:8415:27)
    at waitForServerPrefetch (/projects/example-vue/node_modules/vue-server-renderer/build.dev.js:8287:3)
    at renderComponentInner (/projects/example-vue/node_modules/vue-server-renderer/build.dev.js:8426:3)
    at renderComponent (/projects/example-vue/node_modules/vue-server-renderer/build.dev.js:8383:5)
[module] VS Modules registration finished. { succesfulyRegistered: '0 / 0', registrationOrder: [] }
Calling asyncData for Error page Thu Jan 28 2021 01:49:34 GMT+0000 (Coordinated Universal Time) null
Top-most asyncData executed null
HTML Minifier is enabled
whole request [/error]: 481ms
```

Any thoughts?

Thanks!

**Comment by jissereitsma** [comment]
Amongst the errors, I see a message like `homepage/fetchNewCollection`. So in your source you are making use of this Vuex store, while it is not being registered. Are you sure it is still included in your theme entry file? If you simply copied the `index.js.dist` file into the `index.js` file of your theme, then indeed this is expected. That's why the file is ending with `.dist`. You as a site developer need to make choices here. If you do want to build a project that equals the VSF1 demo, then this requires a bit more work. But if you are actually customizing things for a customer, I doubt that the `fetchNewCollection` store is the exact thing you want. Hence, most developers remove it.

**Comment by davidwindell** [comment]
@jissereitsma thanks so much for the quick reply, I am only really responsible for the devops setup of our vsf infrastructure so probably shouldn't have attempted to set up a parent theme and leave that to the front-end team next time! I had naively assumed it would "just work" i.e. identical to capybarra (a bit like Magento theme inheritance) unless we changed something.

**Comment by davidwindell** [comment]
Just for future reference:

`export { themeEntry, initTheme } from '../capybara/index';` in index.js does exactly what I had expected the theme to do :)

**Comment by jissereitsma** [comment]
True, that would work for a demo. But having said that, the objective of a demo would be to simply have Capybara running. The objective of a child theme would be to allow for customizing. And the first thing I would recommend people to do when starting customization, is to remove things you don't need. By inheriting the entire `index.js` definition of Capybara, you are inheriting exactly that what you would like to customize :) I hope that makes sense.

**Comment by davidwindell** [comment]
Understood, yes that makes much more sense now - thank you for explaining, I really appreciate it and I think the front-end team is going to be pleased when they see this inheritance working!
